name: Lint markdown

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use latest Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint markdown
        run: npx remark docs/ --ext .md --use remark-preset-lint-consistent --use remark-preset-lint-recommended --frail
